name = "url-shortener"
compatibility_date = "2024-08-20"
pages_build_output_dir = "./dist"

[vars]
MY_VAR = "Hono"

[[kv_namespaces]]
binding = "KV"
id = "8293b62a6e434db7a1bb6edbc2c5cc49"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

